<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" fill="none" stroke="#8a8f98" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <path d="M4 5h16"/>
  <path d="M4 12h16"/>
  <path d="M4 19h16"/>
  <path d="M7 5v14"/>
  <path d="M12 5v14"/>
  <path d="M17 5v14"/>
  <path d="M7 12l5 -7"/>
  <path d="M12 19l5 -7"/>
</svg>
